### PR TITLE
Converting to  .adoc

### PR DESCRIPTION
**Pull request by ericsjogren**

### CODE REVIEW

**Comment by ericsjogren** [comment]
I must say that i don't get why we use `.adoc` when the rendering clearly is not working for this format and most of the files already are `.md`

**Comment by psvanstrom** [comment]
I will happily forward that question to @minisu who was the initial creator of the documentation ;)

**Comment by minisu** [comment]
@ericsjogren Good question! :-) Not sure what you mean by _"rendering clearly is not working"_ but I guess that's not your main point anyway.

This repo was created by the PartnerApps team as a quick-n-dirty way to document iZettle's (other teams') APIs for external partners. I was assigned the task and did it in Asciidoc since I was used to writing technical documentation in Asciidoc.

The reason why PartnerApps had to do a quick-n-dirty solution was because the teams who owned the APIs didn't want to (or have the time) do a quick solution, but instead planned to setup Swagger sometime in the future. Some months after these docs were written, the ownership were transferred to the teams owning the APIs (this was about a year ago). During this handover, we agreed that teams can document APIs in whichever way they like, as long as they link to the documentation from `README.md`.

**Comment by guillermo-carrasco** [comment]
LET'S DO MARKDOWN! :dancer:

**Comment by ericsjogren** [comment]
@minisu Thanks for the explanation! 

I should have made it clearer what i mean by rendering: If you use a previewer or run the asciidoctor program to generate a html document you a totally different results (visually) on github which makes the only way to actually check wether it looks decent is to push and preview it here which is a cumbersome process. However if you use .md or use the supported .md elements it looks as expected. 

So maybe my question should be: how do you actually work with `.adoc` in a good way?

**Comment by minisu** [comment]
I'm no expert, but one issue is that _Asciidoc_ is not exactly the same as _Asciidoctor_ ([differences](http://asciidoctor.org/docs/asciidoc-asciidoctor-diffs/)) and GitHub uses the latter. It's a bit of a mess, but I like Asciidoc for actually writing real stuff (technical documentation, static websites, books, etc.). Markdown in my POV is more limited to simple READMEs, issue comments, Slack messages, etc.

Anyway, I completely support the idea that we should try to stick to Markdown.

**Pull request merged**
