### PR TITLE
Add link to product library swagger documentation

### PR DESCRIPTION
**Pull request by pgisslen**

### CODE REVIEW

**Comment by adamvoncorswant** [comment]
Wow! That a lot of commits for a one-line change :)

**Comment by adamvoncorswant** [comment]
:+1:

**Comment by psvanstrom** [comment]
We still doesn't have the product library in the sandbox environment, so has anything changed since this PR was closed? :) https://github.com/iZettle/api-documentation/pull/5

I like the fact that we make the product library available to our integrators though, and it could probably be sufficient for them to test it in production, but we need to inform them that this particular feature is not (currently) available in the sandbox test environment.

**Comment by adamvoncorswant** [comment]
Ah, my memory is great but short :)

Yeas, we should add some information about that. Any suggestion as to where? Or should we just deploy the service in the sandbox enviroment?

**Comment by psvanstrom** [comment]
I don't think we should spend time on deploying it on the sandbox environment, since we hopefully will have a functional test environment courtesy of @freddd up and running quite soon.

In the mean time I think we should add a sub page for the product library, where we can explain that it's only accessible in production and link to the Swagger docs from there. I can fix that if you think it's a good idea.

**Comment by adamvoncorswant** [comment]
:+1:

**Pull request merged**
